server:
  port: 8080
  servlet:
    context-path: /


spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500 #일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속석 컨텍스트이 생존 범위를 트랜잭션 범위로 한정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Swagger 3.0지원
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


logging:
  level:
    org.hibernate.type: trace
    com.app: debug #todo 패키지 수정

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

